== Developing with Errai

In this section we will configure GWT devmode to use the JBoss Application Server so that it is not necessary to manually start the server and deploy a war file before running an Application in dev mode.

Before starting this, you should:

* Have downloaded and unzipped JBoss AS 7.1.1.Final

* Have downloaded errai-tutorial (the dev-mode branch)

* Have installed eclipse with the m2e plugin

=== Importing the Project to Eclipse

First we'll need to get the project into Eclipse:

* In the menu, go to "File" > "Import..."
* In the popup window, select "Maven" > "Existing Maven Projects" and
click "Next"
* Click "Browse", find and select the errai-tutorial folder
* Check that there is only one checkbox listed under "Projects" and that
it is selected
* Click "Finished"

=== Verify you have the Dev Mode Branch

The dev-mode branch of errai-tutorial already includes most of the changes necessary for this setup. If you cloned the project with git, you can switch to the dev-mode branch with:

---------------------
git checkout dev-mode
---------------------

=== What's Different

The dev-mode branch uses the newest release of errai. Additionally, we've added a couple new dependencies to the pom:

-------------------------------------------------------------------------------
<dependency>
  <groupId>org.jboss.errai</groupId>
  <artifactId>errai-cdi-jboss</artifactId>
  <version>${errai.version}</version>
</dependency>

<dependency>
  <groupId>org.jboss.errai</groupId>
  <artifactId>errai-client-local-class-hider</artifactId>
  <version>${errai.version}</version>
</dependency>
-------------------------------------------------------------------------------

The first dependency is for the ServletLauncher, which the gwt-maven-plugin will use to control the JBoss AS instance. The second hides client-side classes from JBoss AS, which is necessary since we will be deploying directly from the webapp directory.

Additionally, the configuration for the gwt-maven-plugin has changed:

-------------------------------------------------------------------------------
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>gwt-maven-plugin</artifactId>
  <version>${gwt.version}</version>
  <executions>
    <execution>
      <goals>
        <goal>resources</goal>
        <goal>compile</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <extraJvmArgs>-Xmx712m -XX:CompileThreshold=7000 -XX:MaxPermSize=128M -Derrai.jboss.home=${errai.jboss.home} -Derrai.jboss.javaagent.path=${settings.localRepository}/org/jboss/errai/errai-client-local-class-hider/${errai.version}/errai-client-local-class-hider-${errai.version}.jar</extraJvmArgs>
    <logLevel>INFO</logLevel>
    <noServer>false</noServer>
    <server>org.jboss.errai.cdi.server.gwt.JBossLauncher</server>
    <disableCastChecking>true</disableCastChecking>
    <runTarget>webapp/index.html</runTarget>
    <soyc>false</soyc>
    <hostedWebapp>src/main/webapp</hostedWebapp>
  </configuration>
</plugin>
-------------------------------------------------------------------------------

The main differences in this configuration are:

* the *noServer* option has been set to false
* there is a new *server* property with the fully-qualified classpath of the JBossLauncher
* we've passed some extra properties through *extraJvmArgs*

=== Configuring errai.jboss.home

One of the extra JVM arguments we gave to the gwt-maven-plugin, errai.jboss.home, is used to tell the launcher where $JBOSS_HOME is located. *It is necessary to set this to the path of your $JBOSS_HOME.*

To set this value to your $JBOSS_HOME, find the *properties* tag near the top of the *pom.xml*. You should see a comment:

-------------------------------------------------------------------------------
<!-- Add the absolute path for $JBOSS_HOME here as errai.jboss.home -->
-------------------------------------------------------------------------------

Replace this comment with the absolute path to $JBOSS_HOME so that it looks like:

-------------------------------------------------------------------------------
<errai.jboss.home>$JBOSS_HOME</errai.jboss.home>
-------------------------------------------------------------------------------

=== Running Dev Mode

You should now be able to start the demo in dev mode with this single command:

-------------------------------------------------------------------------------
mvn clean gwt:run
-------------------------------------------------------------------------------

When the GWT Dev Mode window opens, press "Launch Default Browser" to start the app.

=== Debugging with Dev Mode

To debug in dev mode, we will need to set up two remote debuggers: one on port 8000 for the client-side code, and one on port 8001 for the server-side code.

=== Creating a Remote Debug Configuration in Eclipse

* In the menu, go to "Run" > "Debug Configurations..."
* Find and select "Remote Java Application" in the left pane and click
"New Launch Configuration" in the top left corner
* Under "Project" click "Browse" and select the errai-tutorial project.
* Name the configuration and change the port number
* Click "Close", and save the changes when prompted

=== Start Debugging

Once you have your server and client remote debugging profiles setup, here is how you start debugging:

* Run `mvn clean gwt:debug`

* Launch the *client* remote debugger

* *Wait for the "Launch in Broswer" button to appear*, then start the *server* remote debugger

* Press "Launch Default Broswer"

=== Code and Refresh

Client side changes can now be seen instantly by refreshing the browser window. Give it a try and see for yourself!

=== Refreshing Server Code

Server code can be updated in two steps:

* Open a new terminal in the project and run `mvn compile`
* Click the "Restart Server" button in the server tab of the gwt dev mode window

