== Development Mode with Errai

In this section we will configure GWT development mode to use the JBoss Application Server so that it is NOT necessary to manually start the server and deploy a war file before running an Application in dev mode.

Before starting this, you should:

* Have downloaded the errai-tutorial

* Have installed eclipse with the m2e plugin

=== Importing the Project to Eclipse

First we'll need to get the project into Eclipse:

* In the menu, go to "File" > "Import..."
* In the popup window, select "Maven" > "Existing Maven Projects" and
click "Next"
* Click "Browse", find and select the errai-tutorial folder
* Check that there is only one checkbox listed under "Projects" and that
it is selected
* Click "Finished"

=== Setting up DevMode for JBoss AS 7

Note that you will only need to go through this step if you're upgrading an existing Errai App. If you've just downloaded the errai-tutorial this configuration is already set up for you.

Currently to use this feature, you must be using errai 3.0-SNAPSHOT. Here is the main dependency for the DevMode setup.

-------------------------------------------------------------------------------
<dependency>
  <groupId>org.jboss.errai</groupId>
  <artifactId>errai-cdi-jboss</artifactId>
  <version>${errai.version}</version>
</dependency>
-------------------------------------------------------------------------------

This new dependency is a ServletLauncher, which the gwt-maven-plugin will use to control the JBoss AS instance.

Additionally, the plugin configuration has changed. First we have the new gwt-maven-plugin configuration:

-------------------------------------------------------------------------------
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>gwt-maven-plugin</artifactId>
  <version>${gwt.version}</version>
  <executions>
    <execution>
      <goals>
        <goal>resources</goal>
        <goal>compile</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <extraJvmArgs>-Xmx712m -XX:CompileThreshold=7000 -XX:MaxPermSize=128M -Derrai.jboss.home=${errai.jboss.home} -Derrai.jboss.javaagent.path=${settings.localRepository}/org/jboss/errai/errai-client-local-class-hider/${errai.version}/errai-client-local-class-hider-${errai.version}.jar</extraJvmArgs>
    <logLevel>INFO</logLevel>
    <noServer>false</noServer>
    <server>org.jboss.errai.cdi.server.gwt.JBossLauncher</server>
    <disableCastChecking>true</disableCastChecking>
    <runTarget>webapp/index.html</runTarget>
    <soyc>false</soyc>
    <hostedWebapp>src/main/webapp</hostedWebapp>
  </configuration>
</plugin>
-------------------------------------------------------------------------------

The main differences in this configuration are:

* the *noServer* option has been set to false
* there is a new *server* property with the fully-qualified classpath of the JBossLauncher
* we've passed some extra properties through *extraJvmArgs*

Additionally, we have added a new execution for the maven-dependency plugin:

-------------------------------------------------------------------------------
<!-- Unpack jboss-as from maven. Remove this if you wish to use your own jboss/wildfly instance. -->
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-dependency-plugin</artifactId>
  <executions>
    <execution>
      <id>unpack</id>
      <phase>process-resources</phase>
      <goals>
        <goal>unpack</goal>
      </goals>
      <configuration>
        <artifactItems>
          <artifactItem>
            <groupId>org.jboss.as</groupId>
            <artifactId>jboss-as-dist</artifactId>
            <version>${as.version}</version>
            <type>zip</type>
            <overWrite>false</overWrite>
            <outputDirectory>${project.build.directory}</outputDirectory>
          </artifactItem>
        </artifactItems>
      </configuration>
    </execution>
  </executions>
</plugin>
-------------------------------------------------------------------------------

This new execution will unpack a Jboss Application Server and unzip it into your target directory.

Finally, at the top of the pom we've included the following necessary properties:

-------------------------------------------------------------------------------
<properties>
  <errai.version>3.0-SNAPSHOT</errai.version>
  <gwt.version>2.5.1</gwt.version>
  <errai.dev.context>${project.artifactId}</errai.dev.context>
  <as.version>7.1.1.Final</as.version>
  <!-- Add the absolute path for $JBOSS_HOME below to manage another instance -->
  <errai.jboss.home>${project.build.directory}/jboss-as-${as.version}</errai.jboss.home>
</properties>
-------------------------------------------------------------------------------

=== Managing an External Jboss AS (or Wildfly) (**Optional**)

One of the extra JVM arguments we gave to the gwt-maven-plugin, errai.jboss.home, is used to tell the launcher where $JBOSS_HOME is located. *It is necessary to set this to the path of your $JBOSS_HOME.* In the configuration above, this is done for you for the Jboss installation that is provided by maven.

But if you wish to use a different application server (Jboss 7 or Wildfly 8), you can do so by changing the pom property *errai.jboss.home* near the top of the *pom.xml*.

Just find the comment:

-------------------------------------------------------------------------------
<!-- Add the absolute path for $JBOSS_HOME below to manage another instance -->
-------------------------------------------------------------------------------

Then replace the line below with the following, where $JBOSS_HOME is the absolute path to your AS home folder:

-------------------------------------------------------------------------------
<errai.jboss.home>$JBOSS_HOME</errai.jboss.home>
-------------------------------------------------------------------------------

=== Running Dev Mode

You should now be able to start the demo in dev mode with this single command:

-------------------------------------------------------------------------------
mvn clean gwt:run
-------------------------------------------------------------------------------

When the GWT Dev Mode window opens, press "Launch Default Browser" to start the app.

=== Debugging with Dev Mode

To debug in dev mode, we will need to set up two remote debuggers: one on port 8000 for the client-side code, and one on port 8001 for the server-side code.

=== Creating a Remote Debug Configuration in Eclipse

* In the menu, go to "Run" > "Debug Configurations..."
* Find and select "Remote Java Application" in the left pane and click
"New Launch Configuration" in the top left corner
* Under "Project" click "Browse" and select the errai-tutorial project.
* Name the configuration and change the port number
* Click "Close", and save the changes when prompted

=== Start Debugging

Once you have your server and client remote debugging profiles setup, here is how you start debugging:

* Run `mvn clean gwt:debug`

* Launch the *client* remote debugger

* *Wait for the "Launch in Broswer" button to appear*, then start the *server* remote debugger

* Press "Launch Default Broswer"

=== Code and Refresh

Client side changes can now be seen instantly by refreshing the browser window. Give it a try and see for yourself!

=== Refreshing Server Code

Server code can be updated in two steps:

* Open a new terminal in the project and run `mvn compile`
* Click the "Restart Server" button in the server tab of the gwt dev mode window
