Introduction
------------

What's on the Agenda
~~~~~~~~~~~~~~~~~~~~

Welcome to the Errai tutorial. This tutorial is designed to walk you
through getting started with Errai. What exactly does that entail? Here
is an index of the files in this tutorial guide and what they cover:

1.  link:SETUP.adoc[*SETUP*] : Get the tools you need (such as Git, Maven, and JBoss)
2.  link:RUN.adoc[*RUN*] : Run an Errai Application in production mode 
3.  link:DEVELOP.adoc[*DEVELOP*] : Import the project into your IDE and make use of 
development mode. DevMode skips the translation to JavaScript and lets you debug your 
client and server-side logic as Java code in your IDE. It also allows for quick 
"code-test-debug" cycles. Simply refresh your browser window to load changes.
4.  link:FAQ.adoc[*FAQ*] : Answers to frequently asked questions about the dev mode 
setup.

Would you like to contribute information you've learned to this
tutorial? Send a pull request on
https://github.com/errai/errai-tutorial[github]. Community contributions
are cheerfully reviewed and accepted.
